/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.datos;

import dominio.Sistema;
import dominio.Tarifa;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class VerTarifa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerTarifa.class.getName());

    private Sistema modelo;
    
    public VerTarifa(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTarifas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblSur = new javax.swing.JLabel();
        lblEste = new javax.swing.JLabel();
        lblOeste = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfporcentaje = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JToggleButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tarifas");

        jPanel1.setLayout(null);

        tbTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "<1kg", "1-5kg", "5-10kg", "10kg+"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTarifas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbTarifas.setMinimumSize(new java.awt.Dimension(400, 320));
        tbTarifas.setOpaque(false);
        tbTarifas.setRowHeight(21);
        tbTarifas.setShowGrid(true);
        jScrollPane1.setViewportView(tbTarifas);
        if (tbTarifas.getColumnModel().getColumnCount() > 0) {
            tbTarifas.getColumnModel().getColumn(0).setResizable(false);
            tbTarifas.getColumnModel().getColumn(1).setResizable(false);
            tbTarifas.getColumnModel().getColumn(2).setResizable(false);
            tbTarifas.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(85, 73, 320, 120);

        jLabel1.setText("Norte");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(42, 92, 31, 17);

        lblSur.setText("Sur");
        jPanel1.add(lblSur);
        lblSur.setBounds(54, 163, 19, 17);

        lblEste.setText("Este");
        jPanel1.add(lblEste);
        lblEste.setBounds(47, 140, 26, 17);

        lblOeste.setText("Oeste");
        jPanel1.add(lblOeste);
        lblOeste.setBounds(38, 115, 35, 17);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        jPanel1.add(btnModificar);
        btnModificar.setBounds(321, 219, 84, 23);

        jLabel5.setText("% modificacion");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(94, 222, 91, 17);

        tfporcentaje.addActionListener(this::tfporcentajeActionPerformed);
        jPanel1.add(tfporcentaje);
        tfporcentaje.setBounds(191, 219, 85, 23);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(270, 260, 135, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(150, 260, 108, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         int porcentaje = 0;
        boolean cumple = false;
        try {
            porcentaje = Integer.parseInt(tfporcentaje.getText()) ;
    
            cumple = true;
            
        } catch (NumberFormatException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Ingrese solamente numeros en porcentaje");
        }
        if (cumple){
            for(int i =0;i < modelo.getTarifas().size();i++ ){
                Tarifa t = modelo.getTarifas().get(i);
                
                for(int j = 0; j<4; j++){
                    int calculo = (int) Math.round(t.getPrecios()[j] * (1 + porcentaje / 100.0));
                    tbTarifas.setValueAt(calculo, i, j);
                    t.getPrecios()[j] = calculo;
                }
        
            }             
        }
      
        
       
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tfporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfporcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfporcentajeActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    //Metodos 
   private void cargarTabla(){
       
       for(int i =0;i < modelo.getTarifas().size();i++ ){
        Tarifa t = modelo.getTarifas().get(i);
           for(int j = 0; j<4; j++){
               tbTarifas.setValueAt(t.getPrecios()[j], i, j);
           }
        
        }       
   }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEste;
    private javax.swing.JLabel lblOeste;
    private javax.swing.JLabel lblSur;
    private javax.swing.JTable tbTarifas;
    private javax.swing.JTextField tfporcentaje;
    // End of variables declaration//GEN-END:variables


}
