/**
 * Michelle Katz 220144 
 * Samuel Alzamendi 355626
 */
package interfaz.datos;

import dominio.Sistema;
import dominio.Tarifa;
import javax.swing.JOptionPane;
import persistencia.ArchivoGrabacion;

/**
 *
 * @author samue
 */
public class VerTarifa extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerTarifa.class.getName());

    private Sistema modelo;

    public VerTarifa(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        cargarTabla();
        guardarBackup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTarifas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblSur = new javax.swing.JLabel();
        lblEste = new javax.swing.JLabel();
        lblOeste = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfporcentaje = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tarifas");

        jPanel1.setMinimumSize(new java.awt.Dimension(426, 300));
        jPanel1.setLayout(null);

        tbTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "<1kg", "1-5kg", "5-10kg", "10kg+"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTarifas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbTarifas.setMinimumSize(new java.awt.Dimension(400, 320));
        tbTarifas.setOpaque(false);
        tbTarifas.setRowHeight(21);
        tbTarifas.setShowGrid(true);
        jScrollPane1.setViewportView(tbTarifas);
        if (tbTarifas.getColumnModel().getColumnCount() > 0) {
            tbTarifas.getColumnModel().getColumn(0).setResizable(false);
            tbTarifas.getColumnModel().getColumn(1).setResizable(false);
            tbTarifas.getColumnModel().getColumn(2).setResizable(false);
            tbTarifas.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 70, 320, 120);

        jLabel1.setText("Norte");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 100, 50, 17);

        lblSur.setText("Sur");
        jPanel1.add(lblSur);
        lblSur.setBounds(30, 160, 50, 17);

        lblEste.setText("Este");
        jPanel1.add(lblEste);
        lblEste.setBounds(30, 140, 50, 17);

        lblOeste.setText("Oeste");
        jPanel1.add(lblOeste);
        lblOeste.setBounds(30, 120, 50, 17);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        jPanel1.add(btnModificar);
        btnModificar.setBounds(230, 200, 130, 30);

        jLabel5.setText("% modificacion");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 210, 130, 17);

        tfporcentaje.setPreferredSize(new java.awt.Dimension(64, 36));
        tfporcentaje.addActionListener(this::tfporcentajeActionPerformed);
        jPanel1.add(tfporcentaje);
        tfporcentaje.setBounds(130, 200, 90, 30);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(140, 250, 135, 30);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(290, 250, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int porcentaje = 0;
        boolean cumple = false;
        try {
            porcentaje = Integer.parseInt(tfporcentaje.getText());
            cumple = true;
        } catch (NumberFormatException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Ingrese solamente numeros en porcentaje");
        }
        if (cumple) {
            boolean cumplePrecio = true;
            for (int i = 0; i < modelo.getTarifas().size(); i++) {
                Tarifa t = modelo.getTarifas().get(i);
                for (int j = 0; j < 4 && cumplePrecio; j++) {
                    int calculo = (int) Math.round(t.getPrecios()[j] * (1 + porcentaje / 100.0));
                    if(calculo < 0) {
                         JOptionPane.showMessageDialog(this, "Error... El precio no puede ser negativo");
                         cumplePrecio = false;
                    }
                }

            }if (cumplePrecio) {
                for (int i = 0; i < modelo.getTarifas().size(); i++) {
                    Tarifa t = modelo.getTarifas().get(i);
                    for (int j = 0; j < 4; j++) {
                        int calculo = (int) Math.round(t.getPrecios()[j] * (1 + porcentaje / 100.0));
                        tbTarifas.setValueAt(calculo, i, j);
                        t.getPrecios()[j] = calculo;
                    }
                }
            }
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void tfporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfporcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfporcentajeActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ArchivoGrabacion grab = new ArchivoGrabacion("TARIFAS.TXT");

        for (int i = 0; i < modelo.getTarifas().size(); i++) {
            Tarifa t = modelo.getTarifas().get(i);
            String linea = t.getZona().toString() + "#";
            for (int j = 0; j < 4; j++) {
                linea += t.getPrecios()[j];
                if (j < 3) {
                    linea += ",";
                }
            }
            grab.grabarLinea(linea);

        }

        grab.cerrar();
        modelo.registrarTransaccion("Modificación de tarifas");
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      
      //gardamos precios originales al apretar cancelar - Precios originales creada abajo con el metodo guardarBackup()
       for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            modelo.getTarifas().get(i).getPrecios()[j] = preciosOriginales[i][j];
        } 
         }
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    //Metodos 
    private void cargarTabla() {

        for (int i = 0; i < modelo.getTarifas().size(); i++) {
            Tarifa t = modelo.getTarifas().get(i);
            for (int j = 0; j < 4; j++) {
                tbTarifas.setValueAt(t.getPrecios()[j], i, j);
            }

        }
    }

    private int[][] preciosOriginales;
    private void guardarBackup() {
        preciosOriginales = new int[4][4];
        for (int i = 0; i < 4 ; i++) {
            for (int j = 0; j < 4; j++) {
                preciosOriginales[i][j] = modelo.getTarifas().get(i).getPrecios()[j];
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEste;
    private javax.swing.JLabel lblOeste;
    private javax.swing.JLabel lblSur;
    private javax.swing.JTable tbTarifas;
    private javax.swing.JTextField tfporcentaje;
    // End of variables declaration//GEN-END:variables

}
