/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.Reportes;

import dominio.Cliente;
import dominio.Envio;
import dominio.Paquete;
import dominio.Sistema;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class PaquetesPorEstado extends javax.swing.JFrame implements Observer {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaquetesPorEstado.class.getName());

    private Sistema modelo;

    public PaquetesPorEstado(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        ImageIcon original = new ImageIcon(getClass().getResource("/interfaz/Imagenes/MapaUruguay.jpeg"));
        Image escalada = original.getImage().getScaledInstance(
                lblMapaUruguay.getWidth(), lblMapaUruguay.getHeight(), Image.SCALE_SMOOTH);
        lblMapaUruguay.setIcon(new ImageIcon(escalada));
        cargarTabla();
        modelo.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMain = new javax.swing.JPanel();
        lblEste = new javax.swing.JLabel();
        lblEnviado = new javax.swing.JLabel();
        lblOeste = new javax.swing.JLabel();
        lblNorte = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblPendiente = new javax.swing.JLabel();
        lblOesteMapa = new javax.swing.JLabel();
        lblRecibido = new javax.swing.JLabel();
        lblSur = new javax.swing.JLabel();
        tEnvios = new javax.swing.JTable();
        lblSurMapa = new javax.swing.JLabel();
        lblEsteMapa = new javax.swing.JLabel();
        lblNorteMapa = new javax.swing.JLabel();
        lblMapaUruguay = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paquetes por estado");

        pMain.setLayout(null);

        lblEste.setText("Este");
        pMain.add(lblEste);
        lblEste.setBounds(6, 94, 54, 17);

        lblEnviado.setText("Enviado");
        pMain.add(lblEnviado);
        lblEnviado.setBounds(208, 6, 103, 17);

        lblOeste.setText("Oeste");
        pMain.add(lblOeste);
        lblOeste.setBounds(6, 50, 54, 17);

        lblNorte.setText("Norte");
        pMain.add(lblNorte);
        lblNorte.setBounds(6, 28, 54, 17);

        lblTotal.setText("Total");
        pMain.add(lblTotal);
        lblTotal.setBounds(466, 6, 103, 17);

        lblPendiente.setText("Pendiente");
        pMain.add(lblPendiente);
        lblPendiente.setBounds(78, 6, 103, 17);

        lblOesteMapa.setBackground(new java.awt.Color(255, 255, 51));
        lblOesteMapa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblOesteMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOesteMapa.setText("Oeste");
        lblOesteMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblOesteMapa.setOpaque(true);
        lblOesteMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOesteMapaMouseEntered(evt);
            }
        });
        pMain.add(lblOesteMapa);
        lblOesteMapa.setBounds(90, 190, 52, 33);

        lblRecibido.setText("Recibido");
        pMain.add(lblRecibido);
        lblRecibido.setBounds(337, 6, 103, 17);

        lblSur.setText("Sur");
        pMain.add(lblSur);
        lblSur.setBounds(6, 72, 54, 17);

        tEnvios.setBackground(new java.awt.Color(0, 0, 0));
        tEnvios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tEnvios.setForeground(new java.awt.Color(255, 255, 255));
        tEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pendiente", "Enviado", "Recibido", "Total"
            }
        ));
        tEnvios.setGridColor(new java.awt.Color(255, 255, 255));
        tEnvios.setShowGrid(true);
        tEnvios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tEnviosMouseClicked(evt);
            }
        });
        pMain.add(tEnvios);
        tEnvios.setBounds(78, 30, 514, 80);

        lblSurMapa.setBackground(new java.awt.Color(255, 255, 51));
        lblSurMapa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSurMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSurMapa.setText("Sur");
        lblSurMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSurMapa.setOpaque(true);
        lblSurMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSurMapaMouseEntered(evt);
            }
        });
        pMain.add(lblSurMapa);
        lblSurMapa.setBounds(150, 290, 52, 33);

        lblEsteMapa.setBackground(new java.awt.Color(255, 255, 51));
        lblEsteMapa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblEsteMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEsteMapa.setText("Este");
        lblEsteMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblEsteMapa.setOpaque(true);
        lblEsteMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEsteMapaMouseEntered(evt);
            }
        });
        pMain.add(lblEsteMapa);
        lblEsteMapa.setBounds(240, 210, 52, 33);

        lblNorteMapa.setBackground(new java.awt.Color(255, 255, 51));
        lblNorteMapa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblNorteMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNorteMapa.setText("Norte");
        lblNorteMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNorteMapa.setOpaque(true);
        lblNorteMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNorteMapaMouseEntered(evt);
            }
        });
        pMain.add(lblNorteMapa);
        lblNorteMapa.setBounds(170, 130, 52, 33);

        lblMapaUruguay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMapaUruguay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/mapaUruguay.png"))); // NOI18N
        lblMapaUruguay.setText(".");
        lblMapaUruguay.setToolTipText("");
        lblMapaUruguay.setMaximumSize(new java.awt.Dimension(200, 200));
        lblMapaUruguay.setMinimumSize(new java.awt.Dimension(200, 200));
        lblMapaUruguay.setPreferredSize(new java.awt.Dimension(200, 200));
        pMain.add(lblMapaUruguay);
        lblMapaUruguay.setBounds(78, 116, 224, 226);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        pMain.add(btnCerrar);
        btnCerrar.setBounds(470, 313, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        setBounds(0, 0, 610, 379);
    }// </editor-fold>//GEN-END:initComponents

    private void tEnviosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEnviosMouseClicked
        ArrayList<Paquete> paquetes = modelo.getPaquetes();

        int fila = tEnvios.getSelectedRow();
        int columna = tEnvios.getSelectedColumn();
        String zonaRecibida = "";

        if (fila == 0) {
            zonaRecibida = "Norte";
        } else if (fila == 1) {
            zonaRecibida = "Oeste";
        } else if (fila == 2) {
            zonaRecibida = "Sur";
        } else if (fila == 3) {
            zonaRecibida = "Este";
        }

        String estadoRecibido = "";
        if (columna == 0) {
            estadoRecibido = "Pendiente";
        } else if (columna == 1) {
            estadoRecibido = "Enviado";
        } else if (columna == 2) {
            estadoRecibido = "Recibido";
        }

        String zona = "";
        String estado = "";
        String nombreCliente = "";
        String nombreDepa = "";

        ArrayList<String> nombresClientes = new ArrayList();
        ArrayList<String> nombresDepa = new ArrayList();

        int cont = -1;
        int contDepa = -1;

        if (columna < 3) {
            for (int i = 0; i < paquetes.size(); i++) {

                zona = paquetes.get(i).getDepartamento().getZona().getNombre();
                estado = paquetes.get(i).getEstado();

                if (zona.equalsIgnoreCase(zonaRecibida)) {
                    nombreCliente = paquetes.get(i).getCliente().getNombre();
                    if (estado.equalsIgnoreCase(estadoRecibido)) {

                        boolean clienteNom = true;
                        // clientes
                        if (cont == -1) {
                            nombresClientes.add(nombreCliente);
                            cont += 2;
                        } else {
                            for (int j = 0; j < nombresClientes.size(); j++) {
                                if (nombresClientes.get(j).equalsIgnoreCase(nombreCliente)) {
                                    clienteNom = false;
                                }
                            }
                            if (clienteNom) {
                                cont += 1;
                                nombresClientes.add(nombreCliente);
                            }
                        }// if nombres clientes

                        // departamento
                        boolean depaNom = true;
                        nombreDepa = paquetes.get(i).getDepartamento().getNombre();
                        if (contDepa == -1) {
                            nombresDepa.add(nombreDepa);
                            contDepa += 1;
                        } else {
                            for (int j = 0; j < nombresDepa.size() && depaNom; j++) {
                                if (nombresDepa.get(j).equalsIgnoreCase(nombreDepa)) {
                                    depaNom = false;
                                }
                            }
                            if (depaNom) {
                                nombresDepa.add(nombreDepa);
                            }
                        }// if departamentos

                    }// if estados
                }// if zonas
            }// for paqutes
            String depas = "";
            for (int k = 0; k < nombresDepa.size(); k++) {
                depas = depas + nombresDepa.get(k) + "\n";
            }
            if (cont == -1) {
                cont = 0;
            }

            String mostrar = "Clientes distintos: " + cont + "\n Departmentos: " + depas;
            JOptionPane.showMessageDialog(this, mostrar);

        }

    }//GEN-LAST:event_tEnviosMouseClicked

    private void lblNorteMapaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNorteMapaMouseEntered
        int nP = 0;
        int nE = 0;
        int nR = 0;

        ArrayList<Paquete> paquetes = modelo.getPaquetes();

        for (int h = 0; h < paquetes.size(); h++) {
            String zona = paquetes.get(h).getDepartamento().getZona().getNombre();
            String estado = paquetes.get(h).getEstado();

            if (zona.equalsIgnoreCase("Norte")) {

                if (estado.equalsIgnoreCase("Pendiente")) {
                    //tbTarifas.setValueAt(t.getPrecios()[j], i, j);
                    nP += 1;

                } else if (estado.equalsIgnoreCase("Enviado")) {
                    nE += 1;

                } else if (estado.equalsIgnoreCase("Recibido")) {
                    nR += 1;

                }

            }
        }

        JOptionPane.showMessageDialog(this, "Pendiente: " + nP + "\nEnviado: " + nE + "\nRecibido: " + nR);
    }//GEN-LAST:event_lblNorteMapaMouseEntered

    private void lblEsteMapaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsteMapaMouseEntered
        // TODO add your handling code here:
        ArrayList<Paquete> paquetes = modelo.getPaquetes();
        int eP = 0;
        int eE = 0;
        int eR = 0;
        for (int h = 0; h < paquetes.size(); h++) {
            String zona = paquetes.get(h).getDepartamento().getZona().getNombre();
            String estado = paquetes.get(h).getEstado();
            if (zona.equalsIgnoreCase("Este")) {

                if (estado.equalsIgnoreCase("Pendiente")) {
                    eP += 1;

                } else if (estado.equalsIgnoreCase("Enviado")) {
                    eE += 1;

                } else if (estado.equalsIgnoreCase("Recibido")) {
                    eR += 1;

                }
            }
        }
        JOptionPane.showMessageDialog(this, "Pendiente: " + eP + "\nEnviado: " + eE + "\nRecibido: " + eR);
    }//GEN-LAST:event_lblEsteMapaMouseEntered

    private void lblSurMapaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurMapaMouseEntered
        int sP = 0;
        int sE = 0;
        int sR = 0;

        ArrayList<Paquete> paquetes = modelo.getPaquetes();

        for (int h = 0; h < paquetes.size(); h++) {
            String zona = paquetes.get(h).getDepartamento().getZona().getNombre();
            String estado = paquetes.get(h).getEstado();

            if (zona.equalsIgnoreCase("Sur")) {

                if (estado.equalsIgnoreCase("Pendiente")) {
                    sP += 1;

                } else if (estado.equalsIgnoreCase("Enviado")) {
                    sE += 1;

                } else if (estado.equalsIgnoreCase("Recibido")) {
                    sR += 1;

                }
            }
        }
        JOptionPane.showMessageDialog(this, "Pendiente: " + sP + "\nEnviado: " + sE + "\nRecibido: " + sR);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSurMapaMouseEntered

    private void lblOesteMapaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOesteMapaMouseEntered
        int oP = 0;
        int oE = 0;
        int oR = 0;

        ArrayList<Paquete> paquetes = modelo.getPaquetes();

        for (int h = 0; h < paquetes.size(); h++) {
            String zona = paquetes.get(h).getDepartamento().getZona().getNombre();
            String estado = paquetes.get(h).getEstado();
            if (zona.equalsIgnoreCase("Oeste")) {

                if (estado.equalsIgnoreCase("Pendiente")) {
                    oP += 1;

                } else if (estado.equalsIgnoreCase("Enviado")) {
                    oE += 1;

                } else if (estado.equalsIgnoreCase("Recibido")) {
                    oR += 1;

                }
            }
        }
        JOptionPane.showMessageDialog(this, "Pendiente: " + oP + "\nEnviado: " + oE + "\nRecibido: " + oR);

    }//GEN-LAST:event_lblOesteMapaMouseEntered

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    public void cargarTabla() {
        ArrayList<Paquete> paquetes = modelo.getPaquetes();

        int totalN = 0;
        int totalS = 0;
        int totalE = 0;
        int totalO = 0;

        int nP = 0;
        int nE = 0;
        int nR = 0;

        int sP = 0;
        int sE = 0;
        int sR = 0;

        int eP = 0;
        int eE = 0;
        int eR = 0;

        int oP = 0;
        int oE = 0;
        int oR = 0;

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                tEnvios.setValueAt(0, i, j);
            }
        }

        for (int h = 0; h < paquetes.size(); h++) {
            String zona = paquetes.get(h).getDepartamento().getZona().getNombre();
            String estado = paquetes.get(h).getEstado();
//            for (int i = 0; i < 4; i++) {
//                for (int j = 0; j < 4; j++) {
            if (zona.equalsIgnoreCase("Norte")) {
                totalN += 1;
                if (estado.equalsIgnoreCase("Pendiente")) {
                    //tbTarifas.setValueAt(t.getPrecios()[j], i, j);
                    nP += 1;
                    tEnvios.setValueAt(nP, 0, 0);
                } else if (estado.equalsIgnoreCase("Enviado")) {
                    nE += 1;
                    tEnvios.setValueAt(nE, 0, 1);

                } else if (estado.equalsIgnoreCase("Recibido")) {
                    nR += 1;
                    tEnvios.setValueAt(nR, 0, 2);
                }

            } else if (zona.equalsIgnoreCase("Oeste")) {
                totalO += 1;

                if (estado.equalsIgnoreCase("Pendiente")) {
                    oP += 1;
                    tEnvios.setValueAt(oP, 1, 0);
                } else if (estado.equalsIgnoreCase("Enviado")) {
                    oE += 1;
                    tEnvios.setValueAt(oE, 1, 1);
                } else if (estado.equalsIgnoreCase("Recibido")) {
                    oR += 1;
                    tEnvios.setValueAt(oR, 1, 2);
                }
            } else if (zona.equalsIgnoreCase("Sur")) {
                totalS += 1;

                if (estado.equalsIgnoreCase("Pendiente")) {
                    sP += 1;
                    tEnvios.setValueAt(sP, 2, 0);
                } else if (estado.equalsIgnoreCase("Enviado")) {
                    sE += 1;
                    tEnvios.setValueAt(sE, 2, 1);
                } else if (estado.equalsIgnoreCase("Recibido")) {
                    sR += 1;
                    tEnvios.setValueAt(sR, 2, 2);
                }

            } else if (zona.equalsIgnoreCase("Este")) {
                totalE += 1;

                if (estado.equalsIgnoreCase("Pendiente")) {
                    eP += 1;
                    tEnvios.setValueAt(eP, 3, 0);
                } else if (estado.equalsIgnoreCase("Enviado")) {
                    eE += 1;
                    tEnvios.setValueAt(eE, 3, 1);
                } else if (estado.equalsIgnoreCase("Recibido")) {
                    eR += 1;
                    tEnvios.setValueAt(eR, 3, 2);
                }

            }// if de zonas

            tEnvios.setValueAt(totalN, 0, 3);
            tEnvios.setValueAt(totalO, 1, 3);
            tEnvios.setValueAt(totalS, 2, 3);
            tEnvios.setValueAt(totalE, 3, 3);

            //}// for 3
            //}// for 2
        }// for 1

    }// metodo


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel lblEnviado;
    private javax.swing.JLabel lblEste;
    private javax.swing.JLabel lblEsteMapa;
    private javax.swing.JLabel lblMapaUruguay;
    private javax.swing.JLabel lblNorte;
    private javax.swing.JLabel lblNorteMapa;
    private javax.swing.JLabel lblOeste;
    private javax.swing.JLabel lblOesteMapa;
    private javax.swing.JLabel lblPendiente;
    private javax.swing.JLabel lblRecibido;
    private javax.swing.JLabel lblSur;
    private javax.swing.JLabel lblSurMapa;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pMain;
    private javax.swing.JTable tEnvios;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        cargarTabla();
    }
}
