/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.Reportes;

import dominio.Sistema;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author samue
 */
public class PaquetesPorEstado extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaquetesPorEstado.class.getName());

    private Sistema modelo;
    
    public PaquetesPorEstado(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        ImageIcon original = new ImageIcon(getClass().getResource("/interfaz/Imagenes/MapaUruguay.jpeg"));
        Image escalada = original.getImage().getScaledInstance(
        lblMapaUruguay.getWidth(), lblMapaUruguay.getHeight(), Image.SCALE_SMOOTH);
        lblMapaUruguay.setIcon(new ImageIcon(escalada));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMain = new javax.swing.JPanel();
        lblEste = new javax.swing.JLabel();
        lblEnviado = new javax.swing.JLabel();
        lblOeste = new javax.swing.JLabel();
        lblNorte = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblPendiente = new javax.swing.JLabel();
        lblOesteMapa = new javax.swing.JLabel();
        lblRecibido = new javax.swing.JLabel();
        lblSur = new javax.swing.JLabel();
        tEnvios = new javax.swing.JTable();
        lblSurMapa = new javax.swing.JLabel();
        lblEsteMapa = new javax.swing.JLabel();
        lblNorteMapa = new javax.swing.JLabel();
        lblMapaUruguay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paquetes por estado");

        pMain.setLayout(null);

        lblEste.setText("Este");
        pMain.add(lblEste);
        lblEste.setBounds(6, 94, 54, 16);

        lblEnviado.setText("Enviado");
        pMain.add(lblEnviado);
        lblEnviado.setBounds(208, 6, 103, 16);

        lblOeste.setText("Oeste");
        pMain.add(lblOeste);
        lblOeste.setBounds(6, 50, 54, 16);

        lblNorte.setText("Norte");
        pMain.add(lblNorte);
        lblNorte.setBounds(6, 28, 54, 16);

        lblTotal.setText("Total");
        pMain.add(lblTotal);
        lblTotal.setBounds(466, 6, 103, 16);

        lblPendiente.setText("Pendiente");
        pMain.add(lblPendiente);
        lblPendiente.setBounds(78, 6, 103, 16);

        lblOesteMapa.setBackground(new java.awt.Color(255, 255, 51));
        lblOesteMapa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblOesteMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOesteMapa.setText("Oeste");
        lblOesteMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblOesteMapa.setOpaque(true);
        pMain.add(lblOesteMapa);
        lblOesteMapa.setBounds(90, 190, 52, 33);

        lblRecibido.setText("Recibido");
        pMain.add(lblRecibido);
        lblRecibido.setBounds(337, 6, 103, 16);

        lblSur.setText("Sur");
        pMain.add(lblSur);
        lblSur.setBounds(6, 72, 54, 16);

        tEnvios.setBackground(new java.awt.Color(0, 0, 0));
        tEnvios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tEnvios.setForeground(new java.awt.Color(255, 255, 255));
        tEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pendiente", "Enviado", "Recibido", "Total"
            }
        ));
        tEnvios.setGridColor(new java.awt.Color(255, 255, 255));
        tEnvios.setShowGrid(true);
        pMain.add(tEnvios);
        tEnvios.setBounds(78, 30, 514, 80);

        lblSurMapa.setBackground(new java.awt.Color(255, 255, 51));
        lblSurMapa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSurMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSurMapa.setText("Sur");
        lblSurMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSurMapa.setOpaque(true);
        pMain.add(lblSurMapa);
        lblSurMapa.setBounds(150, 290, 52, 33);

        lblEsteMapa.setBackground(new java.awt.Color(255, 255, 51));
        lblEsteMapa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblEsteMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEsteMapa.setText("Este");
        lblEsteMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblEsteMapa.setOpaque(true);
        pMain.add(lblEsteMapa);
        lblEsteMapa.setBounds(240, 210, 52, 33);

        lblNorteMapa.setBackground(new java.awt.Color(255, 255, 51));
        lblNorteMapa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblNorteMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNorteMapa.setText("Norte");
        lblNorteMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNorteMapa.setOpaque(true);
        pMain.add(lblNorteMapa);
        lblNorteMapa.setBounds(170, 130, 52, 33);

        lblMapaUruguay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMapaUruguay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/mapaUruguay.png"))); // NOI18N
        lblMapaUruguay.setText(".");
        lblMapaUruguay.setToolTipText("");
        lblMapaUruguay.setMaximumSize(new java.awt.Dimension(200, 200));
        lblMapaUruguay.setMinimumSize(new java.awt.Dimension(200, 200));
        lblMapaUruguay.setPreferredSize(new java.awt.Dimension(200, 200));
        pMain.add(lblMapaUruguay);
        lblMapaUruguay.setBounds(78, 116, 224, 226);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 614, 357);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEnviado;
    private javax.swing.JLabel lblEste;
    private javax.swing.JLabel lblEsteMapa;
    private javax.swing.JLabel lblMapaUruguay;
    private javax.swing.JLabel lblNorte;
    private javax.swing.JLabel lblNorteMapa;
    private javax.swing.JLabel lblOeste;
    private javax.swing.JLabel lblOesteMapa;
    private javax.swing.JLabel lblPendiente;
    private javax.swing.JLabel lblRecibido;
    private javax.swing.JLabel lblSur;
    private javax.swing.JLabel lblSurMapa;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pMain;
    private javax.swing.JTable tEnvios;
    // End of variables declaration//GEN-END:variables
}
