/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interzaf;

/**
 *
 * @author samue
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mDatos = new javax.swing.JMenu();
        mClientes = new javax.swing.JMenu();
        mFuncionario = new javax.swing.JMenu();
        mTarifa = new javax.swing.JMenu();
        mPaquetes = new javax.swing.JMenu();
        mIngreso = new javax.swing.JMenu();
        mEnvio = new javax.swing.JMenu();
        mRecepcion = new javax.swing.JMenu();
        mReportes = new javax.swing.JMenu();
        mPaquetesEstado = new javax.swing.JMenu();
        mConsultaCliente = new javax.swing.JMenu();
        mLogTransaccion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        javax.swing.GroupLayout pContenedorLayout = new javax.swing.GroupLayout(pContenedor);
        pContenedor.setLayout(pContenedorLayout);
        pContenedorLayout.setHorizontalGroup(
            pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        pContenedorLayout.setVerticalGroup(
            pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        mDatos.setText("Datos");

        mClientes.setText("Clientes");
        mDatos.add(mClientes);

        mFuncionario.setText("Funcionarios");
        mDatos.add(mFuncionario);

        mTarifa.setText("Tarifa");
        mDatos.add(mTarifa);

        jMenuBar1.add(mDatos);

        mPaquetes.setText("Paquetes");

        mIngreso.setText("Ingreso");
        mPaquetes.add(mIngreso);

        mEnvio.setText("Envío");
        mPaquetes.add(mEnvio);

        mRecepcion.setText("Recepción");
        mPaquetes.add(mRecepcion);

        jMenuBar1.add(mPaquetes);

        mReportes.setText("Reportes");

        mPaquetesEstado.setText("Paquetes por estado");
        mReportes.add(mPaquetesEstado);

        mConsultaCliente.setText("Consulta por cliente");
        mReportes.add(mConsultaCliente);

        mLogTransaccion.setText("Log de transacción");
        mReportes.add(mLogTransaccion);

        jMenuBar1.add(mReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 609, 380);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mConsultaCliente;
    private javax.swing.JMenu mDatos;
    private javax.swing.JMenu mEnvio;
    private javax.swing.JMenu mFuncionario;
    private javax.swing.JMenu mIngreso;
    private javax.swing.JMenu mLogTransaccion;
    private javax.swing.JMenu mPaquetes;
    private javax.swing.JMenu mPaquetesEstado;
    private javax.swing.JMenu mRecepcion;
    private javax.swing.JMenu mReportes;
    private javax.swing.JMenu mTarifa;
    private javax.swing.JPanel pContenedor;
    // End of variables declaration//GEN-END:variables
}
